title: Links & Thinks
url: "https://garden.pcalv.es"
favicon: 🪴

# https://jekyllrb.com/docs/configuration/options/
timezone: Europe/Lisbon

# Remove obsidian-templates and delete the folder if you aren't using Obsidian Templates plugin
exclude: ["_includes/notes_graph.json"]

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities or Dreamhost), set this to 'true'.
use_html_extension: false

# 'True' displays notes graph at bottom of each note
show_notes_graph: false

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# permalink: slug

# Set to 'true' to generate excerpts for pages. Notes are technically pages.
page_excerpts: false

plugins:
  - jekyll-last-modified-at
  - jekyll-regex-replace

collections:
  notes:
    output: true
    permalink: /:slug

  pages:
    output: true
    permalink: /:slug

  tags:
    output: true
    permalink: /tags/:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
  - scope:
      path: "_tags/*.md"
    values:
      layout: "tag"